# Generated by Django 5.1.3 on 2024-11-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catergory',
        ),
    ]
